apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bitcoind.fullname" . }}
  labels:
    app: {{ template "bitcoind.name" . }}
    chart: {{ template "bitcoind.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "bitcoind.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: {{ template "bitcoind.name" . }}
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.configurationFile }}
      initContainers:
        - name: copy-bitcoind-config
          image: busybox
          command: ['sh', '-c', 'cp /configmap/bitcoin.conf /bitcoin/.bitcoin/bitcoin.conf']
          volumeMounts:
            - name: configmap
              mountPath: /configmap
            - name: config
              mountPath: /bitcoin/.bitcoin/
      {{- end }}
      containers:
        - name: {{ template "bitcoind.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            - name: rpc
              containerPort: {{ .Values.service.rpcPort }}
            - name: p2p
              containerPort: {{ .Values.service.p2pPort }}
            - name: testnet
              containerPort: {{ .Values.service.testnetPort }}
            - name: testnetp2pport
              containerPort: {{ .Values.service.testnetP2pPort }}
            - name: zmqrawblockport
              containerPort: {{ .Values.service.zmqRawBlockPort }}
            - name: zmqrawtxport
              containerPort: {{ .Values.service.zmqRawTxPort }}
          volumeMounts:
            - name: data
              mountPath: /bitcoin
            {{- if .Values.configurationFile }}
            - name: config
              mountPath: /bitcoin/.bitcoin/bitcoin.conf
              subPath: bitcoin.conf
            {{- end }}
        {{- if .Values.miningCronjob.enabled }}
        - name: regtest-mining-cronjob
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: ['/bin/sh']
          args:
            - "-c"
            - "while true; do bitcoin-cli -generate 1; sleep {{ .Values.miningCronjob.intervalSeconds }}; done"
          volumeMounts:
            {{- if .Values.configurationFile }}
            - name: config
              mountPath: /bitcoin/.bitcoin/bitcoin.conf
              subPath: bitcoin.conf
            {{- end }}
        {{- end }}
      volumes:
        {{- if .Values.configurationFile }}
        - name: config
          emptyDir: {}
        - name: configmap
          configMap:
            name: {{ template "bitcoind.fullname" . }}
        {{- end }}
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "bitcoind.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
