{{- if .Values.kubetail.clusterAgent.enabled }}
{{- $ds := index .Values "kubetail" "clusterAgent" "daemonSet" -}}
{{- $podTmpl := index .Values "kubetail" "clusterAgent" "podTemplate" }}
{{- $container := index .Values "kubetail" "clusterAgent" "container" -}}
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{ include "kubetail.clusterAgent.daemonSetName" $ }}
  namespace: {{ include "kubetail.namespace" $ }}
  labels:
    {{- include "kubetail.clusterAgent.labels" (list $ $ds.labels) | indent 4 }}
  annotations:
    {{- include "kubetail.annotations" (list $ $ds.annotations) | indent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kubetail.clusterAgent.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubetail.clusterAgent.labels" (list $ $podTmpl.labels) | indent 8 }}
      annotations:
        {{- include "kubetail.annotations" (list $ $podTmpl.annotations) | indent 8 }}
        checksum/config: {{ include "kubetail.clusterAgent.config" $ | sha256sum | quote }}
    spec:
      automountServiceAccountToken: true
      serviceAccountName: {{ include "kubetail.clusterAgent.serviceAccountName" $ }}
      securityContext:
        {{- with $podTmpl.securityContext -}}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
      - name: {{ $container.name }}
        image: {{ include "kubetail.clusterAgent.image" $ }}
        securityContext:
          {{- with $container.securityContext -}}
          {{ toYaml . | nindent 10 }}
          {{- end }}
        imagePullPolicy: {{ .Values.kubetail.clusterAgent.image.pullPolicy }}
        env:
        {{- with $container.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        envFrom:
        {{- with $container.extraEnvFrom }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        args:
        - --config=/etc/kubetail/config.yaml
        ports:
        - name: grpc
          protocol: TCP
          containerPort: {{ .Values.kubetail.clusterAgent.runtimeConfig.ports.grpc }}
        livenessProbe:
          grpc:
            port: {{ .Values.kubetail.clusterAgent.runtimeConfig.ports.grpc }}
          initialDelaySeconds: 5
          timeoutSeconds: 30
          periodSeconds: 3
          failureThreshold: 3
        readinessProbe:
          grpc:
            port: {{ .Values.kubetail.clusterAgent.runtimeConfig.ports.grpc }}
          initialDelaySeconds: 5
          timeoutSeconds: 30
          periodSeconds: 3
          failureThreshold: 3
        resources:
          {{- with $container.resources }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        volumeMounts:
        - name: config
          mountPath: /etc/kubetail
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      {{- with $podTmpl.extraContainers  }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "kubetail.clusterAgent.configMapName" $ }}
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      nodeSelector:
        {{- with $podTmpl.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end}}
      affinity:
        {{- with $podTmpl.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end}}
      tolerations:
      {{- with $podTmpl.tolerations }}
      {{- toYaml . | nindent 6 }}
      {{- end}}
{{- end }}
