{{- if .Values.kubetail.clusterAgent.enabled }}
{{- $sa := index .Values "kubetail" "clusterAgent" "serviceAccount" -}}
kind: ServiceAccount
apiVersion: v1
automountServiceAccountToken: true
metadata:
  name: {{ include "kubetail.clusterAgent.serviceAccountName" $ }}
  namespace: {{ include "kubetail.namespace" $ }}
  labels:
    {{- include "kubetail.clusterAgent.labels" (list $ $sa.labels) | indent 4 }}
  annotations:
    {{- include "kubetail.annotations" (list $ $sa.annotations) | indent 4 }}
{{- end }}
