apiVersion: v1
appVersion: 0.10.2
description: A Scala implementation of a Lightning Network node
engine: gotpl
keywords:
- eclair
- cryptocurrency
- blockchain
- bitcoin
maintainers:
- email: kwinten@flitz.be
  name: kiwiidb
name: eclair
sources:
- https://github.com/kubernetes/charts
version: 0.6.1