{{- if .Values.kubetail.cli.enabled }}
{{- $sa := index .Values "kubetail" "cli" "serviceAccount" -}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "kubetail.cli.serviceAccountName" $ }}
  namespace: {{ include "kubetail.namespace" $ }}
  labels:
    {{- include "kubetail.cli.labels" (list $ $sa.labels) | indent 4 }}
  annotations:
    {{- include "kubetail.annotations" (list $ $sa.annotations) | indent 4 }}
{{- end }}
