apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-microservice.fullname" . }}
  labels:
    {{- include "generic-microservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- if .Values.prometheus.enabled }}
    - port: {{ .Values.prometheus.port }}
      targetPort: prometheus
      protocol: TCP
      name: prometheus
  {{- end }}
  {{- range .Values.extraPorts }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: {{ .protocol }}
      name: {{ .name }}
  {{- end }}
 
  selector:
    {{- include "generic-microservice.selectorLabels" . | nindent 4 }}
