apiVersion: v2
appVersion: "1.0"
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 13.2.23
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 18.4.0
description: Apache Superset is a modern, enterprise-ready business intelligence web
  application
maintainers:
- email: craig@craigrueda.com
  name: craig-rueda
  url: https://github.com/craig-rueda
name: superset
version: 0.6.0
