{
 "title": "Routing",
 "tags": [ "lightning-network" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": "label_values(cluster)" },
   { "name": "job", "label": "job", "query": "label_values(job)" },
   { "name": "HtlcType", "query": "forward,send,receive" }
  ]
 },
 "panels": [
  {
   "title": "HTLC Resolution Rate",
   "type": "graph",
   "description": "The rate at which HTLCs for ${HtlcType}s are settled and failed. Note that these values are recorded since lnd's last restart, and are not persisted. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Resolution Rate" }
   ],
   "targets": [
    {
     "expr": "increase(sum by(outcome)(lnd_htlcs_resolved_htlcs{type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"})[5m:1s])",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "graph",
   "description": "The percentage of ${HtlcType}s that are successfully settled. Note that this rate is tracked since lnd's last restart, and is not persisted over time. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "Success Percentage" }
   ],
   "targets": [
    {
     "expr": "sum(lnd_htlcs_resolved_htlcs{outcome=\"settled\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"})/ sum(lnd_htlcs_resolved_htlcs{type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"})",
     "legendFormat": "settled"
    }
   ]
  },
  {
   "title": "Incoming Channel - Settled",
   "type": "graph",
   "description": "The number of HTLCs for ${HtlcType}s that each channel has settled as the incoming channel. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "HTLC Count" }
   ],
   "targets": [
    {
     "expr": "sum by (chan_in)(lnd_htlcs_resolved_htlcs{outcome=\"settled\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"})",
     "legendFormat": "{{chan_in}}"
    }
   ]
  },
  {
   "title": "Outgoing Channel - Settled",
   "type": "graph",
   "description": "The number of HTLCs for ${HtlcType}s that each channel has settled as the outgoing channel. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "HTLC Count" }
   ],
   "targets": [
    {
     "expr": "sum by (chan_out)(lnd_htlcs_resolved_htlcs{outcome=\"settled\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"})",
     "legendFormat": "{{chan_out}}"
    }
   ]
  },
  {
   "title": "Incoming Channel - Failed",
   "type": "graph",
   "description": "The number of HTLCs for ${HtlcType}s that each channel has failed as the incoming channel. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "HTLC Count" }
   ],
   "targets": [
    {
     "expr": "sum by (chan_in)(lnd_htlcs_resolved_htlcs{outcome=\"failed\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"})",
     "legendFormat": "{{chan_in}}"
    }
   ]
  },
  {
   "title": "Outgoing Channel - Failed",
   "type": "graph",
   "description": "The number of HTLCs for ${HtlcType}s that each channel has failed as the outgoing channel. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "HTLC Count" }
   ],
   "targets": [
    {
     "expr": "sum by (chan_out)(lnd_htlcs_resolved_htlcs{outcome=\"failed\", type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"})",
     "legendFormat": "{{chan_out}}"
    }
   ]
  },
  {
   "title": "Htlc Resolution Time",
   "type": "graph",
   "description": "A frequency distribution of the time ${HtlcType}s have taken to resolve. Note that this value is not tracked for receives.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "HTLC Count" }
   ],
   "targets": [
    {
     "expr": "sum(lnd_htlcs_resolution_time_bucket{le=\"1\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"})",
     "legendFormat": "0-1 seconds"
    },
    {
     "expr": "sum(lnd_htlcs_resolution_time_bucket{le=\"10\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"}) - ignoring(le) sum(lnd_htlcs_resolution_time_bucket{le=\"1\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"})",
     "legendFormat": "1-10 seconds"
    },
    {
     "expr": "sum(lnd_htlcs_resolution_time_bucket{le=\"60\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"}) - ignoring(le) sum(lnd_htlcs_resolution_time_bucket{le=\"10\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"})",
     "legendFormat": "11-60 seconds"
    },
    {
     "expr": "sum(lnd_htlcs_resolution_time_bucket{le=\"120\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"}) - ignoring(le) sum(lnd_htlcs_resolution_time_bucket{le=\"60\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"})",
     "legendFormat": "1-2 minutes"
    },
    {
     "expr": "sum(lnd_htlcs_resolution_time_bucket{le=\"300\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"}) - ignoring(le) sum(lnd_htlcs_resolution_time_bucket{le=\"120\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"})",
     "legendFormat": "2-5 minutes"
    },
    {
     "expr": "sum(lnd_htlcs_resolution_time_bucket{le=\"600\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"}) - ignoring(le) sum(lnd_htlcs_resolution_time_bucket{le=\"300\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"})",
     "legendFormat": "5-10 minutes"
    },
    {
     "expr": "sum(lnd_htlcs_resolution_time_bucket{le=\"3600\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"}) - ignoring(le) sum(lnd_htlcs_resolution_time_bucket{le=\"600\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"})",
     "legendFormat": "10-60 minutes"
    },
    {
     "expr": "sum(lnd_htlcs_resolution_time_bucket{le=\"18000\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"}) - ignoring(le) sum(lnd_htlcs_resolution_time_bucket{le=\"3600\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"})",
     "legendFormat": "1-5 hours"
    },
    {
     "expr": "sum(lnd_htlcs_resolution_time_bucket{le=\"86400\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"}) - ignoring(le) sum(lnd_htlcs_resolution_time_bucket{le=\"18000\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"})",
     "legendFormat": "5-24 hours"
    },
    {
     "expr": "sum(lnd_htlcs_resolution_time_bucket{le=\"604800\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"}) - ignoring(le) sum(lnd_htlcs_resolution_time_bucket{le=\"86400\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"})",
     "legendFormat": "1-7 days"
    },
    {
     "expr": "sum(lnd_htlcs_resolution_time_bucket{le=\"++Inf\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"}) - ignoring(le) sum(lnd_htlcs_resolution_time_bucket{le=\"604800\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"})",
     "legendFormat": "> 7 days"
    }
   ]
  },
  {
   "title": "Average HTLC Resolution Time",
   "type": "graph",
   "description": "The average time taken to settle or fail HTLCs for ${HtlcType}s. Note that this value is not tracked for receives.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(lnd_htlcs_resolution_time_sum{type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"})/sum(lnd_htlcs_resolution_time_count{type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"})",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "Failure Reasons",
   "type": "graph",
   "description": "The reasons provided for htlcs involved in ${HtlcType}s on lnd's channels failing. Note that \"failed_back\" indicates that the payment failed further down the route, and all other failure reasons indicate that your node failed the htlc.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "HTLC Count" }
   ],
   "targets": [
    {
     "expr": "sum by (failure_reason)(lnd_htlcs_resolved_htlcs{outcome=\"failed\",type=\"$HtlcType\",cluster=\"$cluster\",job=\"$job\"})",
     "legendFormat": "{{failure_reason}}"
    }
   ]
  }
 ]
}