{
 "title": "Chain State",
 "tags": [ "lightning-network" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": "label_values(cluster)" },
   { "name": "job", "label": "job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "On-Chain Wallet Balance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "currencyBTC" }
   ],
   "targets": [
    {
     "expr": "lnd_wallet_balance_confirmed_sat{cluster=\"$cluster\",job=\"$job\"}",
     "legendFormat": "conf_sat"
    },
    {
     "expr": "lnd_wallet_balance_unconfirmed_sat{cluster=\"$cluster\",job=\"$job\"}",
     "legendFormat": "unconf_sat"
    }
   ]
  },
  {
   "title": "UTXO Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lnd_utxos_count_confirmed_total{cluster=\"$cluster\",job=\"$job\"}",
     "legendFormat": "num_conf_utxos"
    },
    {
     "expr": "lnd_utxos_count_unconfirmed_total{cluster=\"$cluster\",job=\"$job\"}",
     "legendFormat": "num_unconf_utxos"
    }
   ]
  },
  {
   "title": "UTXO Sizes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "currencyBTC" }
   ],
   "targets": [
    {
     "expr": "lnd_utxos_sizes_avg_sat{cluster=\"$cluster\",job=\"$job\"}",
     "legendFormat": "avg_utxo_size_sat"
    },
    {
     "expr": "lnd_utxos_sizes_max_sat{cluster=\"$cluster\",job=\"$job\"}",
     "legendFormat": "max_utxo_size_sat"
    },
    {
     "expr": "lnd_utxos_sizes_min_sat{cluster=\"$cluster\",job=\"$job\"}",
     "legendFormat": "min_utxo_size_sat"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "lnd_chain_block_height{cluster=\"$cluster\",job=\"$job\"}",
     "legendFormat": "block_height"
    }
   ]
  }
 ]
}