{
 "title": "Go Runtime + Performance",
 "tags": [ "lightning-network" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": "label_values(cluster)" },
   { "name": "job", "label": "job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{cluster=\"$cluster\",job=\"$job\"}[1m])",
     "legendFormat": "cpu_usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{cluster=\"$cluster\",job=\"$job\"}",
     "legendFormat": "res_mem"
    },
    {
     "expr": "process_virtual_memory_bytes{cluster=\"$cluster\",job=\"$job\"}",
     "legendFormat": "virt_mem"
    }
   ]
  },
  {
   "title": "GC Pause Durations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{cluster=\"$cluster\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{cluster=\"$cluster\",job=\"$job\"}",
     "legendFormat": "heap_alloc_bytes"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{cluster=\"$cluster\",job=\"$job\"}",
     "legendFormat": "heap_idle_bytes"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{cluster=\"$cluster\",job=\"$job\"}",
     "legendFormat": "heap_inuse_bytes"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{cluster=\"$cluster\",job=\"$job\"}",
     "legendFormat": "heap_sys_bytes"
    },
    {
     "expr": "go_memstats_heap_released_bytes{cluster=\"$cluster\",job=\"$job\"}",
     "legendFormat": "heap_release_bytes"
    }
   ]
  },
  {
   "title": "Num Heap Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_objects{cluster=\"$cluster\",job=\"$job\"}",
     "legendFormat": "num_heap_objects"
    }
   ]
  },
  {
   "title": "Num Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{cluster=\"$cluster\",job=\"$job\"}",
     "legendFormat": "num_goroutines"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{cluster=\"$cluster\",job=\"$job\"}",
     "legendFormat": "open_fds"
    }
   ]
  }
 ]
}