{{- if .Values.kubetail.clusterAPI.enabled }}
{{- $cfgMap := index .Values "kubetail" "clusterAPI" "configMap" -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "kubetail.clusterAPI.configMapName" $ }}
  namespace: {{ include "kubetail.namespace" $ }}
  labels:
    {{- include "kubetail.clusterAPI.labels" (list $ $cfgMap.labels) | indent 4 }}
  annotations:
    {{- include "kubetail.annotations" (list $ $cfgMap.annotations) | indent 4 }}
data:
  config.yaml: |
    {{- include "kubetail.clusterAPI.config" $ | indent 4 }}
{{- end }}
