{{- if .Values.kubetail.clusterAPI.enabled }}
{{- $secret := index .Values "kubetail" "clusterAPI" "secret" -}}
{{- if $secret.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "kubetail.clusterAPI.secretName" $ }}
  namespace: {{ include "kubetail.namespace" $ }}
  labels:
    {{- include "kubetail.clusterAPI.labels" (list $ $secret.labels) | indent 4 }}
  annotations:
    {{- include "kubetail.annotations" (list $ $secret.annotations) | indent 4 }}
type: Opaque
data:
  {{- include "kubetail.clusterAPI.secretData" $ | nindent 2 }}
{{- end }}
{{- end }}
