{{- if .Values.kubetail.clusterAPI.enabled }}
{{- $sa := index .Values "kubetail" "clusterAPI" "serviceAccount" -}}
kind: ServiceAccount
apiVersion: v1
automountServiceAccountToken: true
metadata:
  name: {{ include "kubetail.clusterAPI.serviceAccountName" $ }}
  namespace: {{ include "kubetail.namespace" $ }}
  labels:
    {{- include "kubetail.clusterAPI.labels" (list $ $sa.labels) | indent 4 }}
  annotations:
    {{- include "kubetail.annotations" (list $ $sa.annotations) | indent 4 }}
{{- end }}
